version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
    command: ["./backend-app"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    command: ["npm", "start"]
